title: Researcher
url: "https://ankitsultana.com"
baseurl: "/researcher"

remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "CV"
   link: "sahil_tyagiCV.pdf"
 - name: "Contact"
   link: "contact"