remote_theme: ankitsultana/researcher@gem
title: Sahil Tyagi
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

include: ["_includes"]

nav:
 - name: "About"
   link: "/"
 - name: "CV"
   link: "sahil_tyagiCV.pdf"
 - name: "Contact"
   link: "contact"